### ISSUE TITLE
wishlist: image, video and sound gallery pages

### ISSUE THREAD

**Issue by kellyhaydon** [bavc/avaa#34]
As seen in the wikimedia sidebar (see screencap)

![screen shot 2017-01-23 at 1 08 36 pm](https://cloud.githubusercontent.com/assets/9436241/22216434/11a48970-e16d-11e6-8bd2-a716ba5523cd.png)

**Comment by kieranjol** [comment]
👍  this would be really handy!

**Comment by pamelajean** [comment]
yes, i really miss the galleries!

**Comment by ablwr** [comment]
An option here might be for someone to create a few simplistic shell scripts that can be run and the results can be dumped into gallery pages. I can't think about how to do this other than this semi-manual process (and since the pages are static, it can't be a cron-job style solution). 

Any takers for implementing a script that can be occasionally run?

The script would have to go through the entire site directory and find links to soundcloud / internet archive and push them all into one page.

Images ARE hosted on the site, but context is important. The script would have to grab up every image and wrap it in a link to the page from which it was found.

Anyway, also very open to other ideas for solving this problem, or if there is a solution that already exists out there for Jekyll-style sites.

**Comment by kellyhaydon** [comment]
It's not perfect, but as a replacement video gallery you us the AV Artifact Atlas tag in archive.org to see the videos as thumbnails. We have an IA collection pending: https://archive.org/search.php?query=subject%3A%22AV+Artifact+Atlas%22&sort=-publicdate&and[]=subject%3A%22AV+Artifact+Atlas%22

**Comment by ryanfb** [comment]
I wonder if [Jekyll data files](https://jekyllrb.com/docs/datafiles/) would be a good way to implement this. You could have `_data/examples.yml` with e.g.:

```
- for_page: skew_error
  type: video
  content:
  - archive: skew_error
  caption: Skew is visible at the top of the screen in this short clip.

- for_page: analog_distortion
  type: audio
  content:
  - soundcloud: 96774470
  caption: Listen to analog distortion on SoundCloud.

- for_page: chrominance_noise
  type: image
  content:
    - file: ChromaNoise_Flat.jpg
```

Then a gallery that looks like:

```
{% for example in site.data.examples %}
{% if example.type == 'video' %}
<a href="{{ site.baseurl }}/artifacts/{{ example.for_page }}.html">{{ site.artifacts[example.for_page].title }}</a>
{{ include example.html example=example }}
{% endif %}
{% endfor %}
```

Then `_includes/examples.html` could use something like:

```
{% if include.example.content.archive %}
<iframe src="https://archive.org/embed/{{ include.example.content.archive }}" width="560" height="315" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
{% elsif include.example.content.soundcloud %}
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/{{ include.example.content.soundcloud }}&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&visual=true"></iframe>
{% elsif include.example.content.file %}
<img src="{{ site.baseurl }}/images/{{ include.example.content.file }}"/>
{% endif %}
{% if include.example.caption %}
<sub>{{ include.example.caption }}</sub>
{% endif %}
```

You could also use this to dynamically build the examples on each page from the same data (loop over the array and output all examples where `for_page` matches `page.url`). Not sure if there's any examples that are on multiple pages - then you would need an array there, and maybe it starts to get too confusing...
